version: '3'
services:
  mysql:
    image: mysql:8.0.33
    hostname: mysql
    env_file: .env
    ports:
      - 3306:3306
    networks:
      - api
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/src
    ports:
      - 3000:3000
    networks:
      - api
networks:
  api:
    driver: bridge  